import type { WorkItem } from "./types"

// Fictional data for visual proofing only. No real customer or financial data.
export const WORK_ITEMS: WorkItem[] = [
  {
    id: "WRK-1042",
    customer: "Acme Foods",
    item: "Credit Limit Increase",
    module: "Customers",
    status: "review",
    owner: { name: "A. Sharma", initials: "AS" },
    ageDays: 2,
    value: 45000,
    nextAction: "Review submitted documents",
    createdAt: "3 days ago",
    submittedAt: "2 days ago",
    activity: [
      { label: "Submitted for review", actor: "A. Sharma", when: "2h ago" },
      { label: "Supporting document added", actor: "R. Mehta", when: "Yesterday" },
      { label: "Record created", actor: "S. Rao", when: "3 days ago" },
    ],
  },
  {
    id: "WRK-1038",
    customer: "Northstar Retail",
    item: "Commercial Terms Renewal",
    module: "Commercials",
    status: "attention",
    owner: { name: "R. Mehta", initials: "RM" },
    ageDays: 6,
    value: 128500,
    nextAction: "Confirm discount tier with sales",
    createdAt: "8 days ago",
    submittedAt: "6 days ago",
    exceptionNote: "Awaiting sales confirmation for 6 days, nearing SLA.",
    activity: [
      { label: "Escalated to sales for confirmation", actor: "R. Mehta", when: "1d ago" },
      { label: "Discount tier flagged as unclear", actor: "System", when: "4 days ago" },
      { label: "Submitted for review", actor: "R. Mehta", when: "6 days ago" },
      { label: "Record created", actor: "R. Mehta", when: "8 days ago" },
    ],
  },
  {
    id: "WRK-1051",
    customer: "Summit Consumer",
    item: "Go-Live Readiness Check",
    module: "Go-Live",
    status: "draft",
    owner: { name: "S. Rao", initials: "SR" },
    ageDays: 1,
    value: null,
    nextAction: "Complete onboarding checklist",
    createdAt: "1 day ago",
    submittedAt: "Not submitted",
    activity: [
      { label: "Record created", actor: "S. Rao", when: "1 day ago" },
    ],
  },
  {
    id: "WRK-1029",
    customer: "Harbor Distribution",
    item: "Suspension Review",
    module: "Suspensions",
    status: "blocked",
    owner: { name: "A. Sharma", initials: "AS" },
    ageDays: 9,
    value: 76200,
    nextAction: "Escalate to credit control",
    createdAt: "12 days ago",
    submittedAt: "9 days ago",
    activity: [
      { label: "Blocked pending credit control decision", actor: "System", when: "9 days ago" },
      { label: "Submitted for review", actor: "A. Sharma", when: "9 days ago" },
      { label: "Record created", actor: "A. Sharma", when: "12 days ago" },
    ],
  },
  {
    id: "WRK-1015",
    customer: "Atlas Manufacturing",
    item: "Ledger Reconciliation",
    module: "Ledger",
    status: "approved",
    owner: { name: "K. Iyer", initials: "KI" },
    ageDays: 3,
    value: 12340,
    nextAction: "Archive",
    createdAt: "5 days ago",
    submittedAt: "3 days ago",
    activity: [
      { label: "Approved", actor: "K. Iyer", when: "2h ago" },
      { label: "Submitted for review", actor: "K. Iyer", when: "3 days ago" },
      { label: "Record created", actor: "K. Iyer", when: "5 days ago" },
    ],
  },
  {
    id: "WRK-1055",
    customer: "Cedar Household",
    item: "New Customer Onboarding",
    module: "Customers",
    status: "review",
    owner: { name: "R. Mehta", initials: "RM" },
    ageDays: 1,
    value: 5600,
    nextAction: "Verify tax registration",
    createdAt: "1 day ago",
    submittedAt: "1 day ago",
    activity: [
      { label: "Submitted for review", actor: "R. Mehta", when: "5h ago" },
      { label: "Record created", actor: "R. Mehta", when: "1 day ago" },
    ],
  },
  {
    id: "WRK-1008",
    customer: "Meridian Foods",
    item: "Commercial Terms Update",
    module: "Commercials",
    status: "draft",
    owner: { name: "S. Rao", initials: "SR" },
    ageDays: 4,
    value: 34900,
    nextAction: "Await pricing sign-off",
    createdAt: "4 days ago",
    submittedAt: "Not submitted",
    activity: [
      { label: "Record created", actor: "S. Rao", when: "4 days ago" },
    ],
  },
  {
    id: "WRK-1061",
    customer: "Bluepeak Consumer",
    item: "Go-Live Checklist",
    module: "Go-Live",
    status: "review",
    owner: { name: "K. Iyer", initials: "KI" },
    ageDays: 2,
    value: null,
    nextAction: "Confirm warehouse mapping",
    createdAt: "2 days ago",
    submittedAt: "1 day ago",
    activity: [
      { label: "Submitted for review", actor: "K. Iyer", when: "Yesterday" },
      { label: "Record created", actor: "K. Iyer", when: "2 days ago" },
    ],
  },
  {
    id: "WRK-1022",
    customer: "Orion Retail",
    item: "Suspension Lift Request",
    module: "Suspensions",
    status: "attention",
    owner: { name: "A. Sharma", initials: "AS" },
    ageDays: 5,
    value: 21000,
    nextAction: "Confirm payment clearance",
    createdAt: "6 days ago",
    submittedAt: "5 days ago",
    exceptionNote: "Payment clearance unconfirmed for 5 days.",
    activity: [
      { label: "Payment clearance requested", actor: "A. Sharma", when: "5 days ago" },
      { label: "Record created", actor: "A. Sharma", when: "6 days ago" },
    ],
  },
  {
    id: "WRK-1003",
    customer: "Crestline Products",
    item: "Ledger Adjustment",
    module: "Ledger",
    status: "approved",
    owner: { name: "R. Mehta", initials: "RM" },
    ageDays: 7,
    value: 9800,
    nextAction: "Close record",
    createdAt: "10 days ago",
    submittedAt: "7 days ago",
    activity: [
      { label: "Approved", actor: "R. Mehta", when: "2 days ago" },
      { label: "Submitted for review", actor: "R. Mehta", when: "7 days ago" },
      { label: "Record created", actor: "R. Mehta", when: "10 days ago" },
    ],
  },
]

export const WORK_SUMMARY = [
  { label: "Needs review", value: 6 },
  { label: "Sent back", value: 3 },
  { label: "Attention", value: 4 },
  { label: "Due soon", value: 2 },
]
